attacks:
  default_interface: "lo"
  default_num_devices: 50
  dhcp:
    default_request_options: "1,3,6"
    default_client_src: []
  arp:
    default_base_ip: "192.168.1."
    default_mac_prefix: "de:ad:00"
    default_interval: 5.0
    default_cycles: 1
  traffic:
    default_bpf_filter: "tcp port 80"
    default_output_file: "capture.pcap"
    default_duration: 0
    default_count: 0
    default_snaplen: 0
    default_promisc: True
