repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--config=config/formatter/.black]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--settings-file=config/formatter/.isort.cfg]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--config=config/linter/.flake8]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        args: [--config=config/linter/.mypy.ini]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0
    hooks:
      - id: clang-format
        args: [-i, -style=file]
        files: netarmageddon/core/traffic_c/.*\.(c|h)$
        additional_dependencies: ['clang-format==14.0.0']
        exclude: \.(o|so|pcap)$

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        args: [
          --config-file=netarmageddon/core/traffic_c/.clang-tidy,
          -p=netarmageddon/core/traffic_c,
          --extra-arg=-Wno-unknown-warning-option,
          --extra-arg=-Wno-unused-command-line-argument
        ]
        language: system
        files: netarmageddon/core/traffic_c/.*\.(c|h)$
        working_dir: netarmageddon/core/traffic_c
