repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        always_run: true
        exclude: ^README.md$
      - id: end-of-file-fixer
        always_run: true
      - id: check-yaml
        always_run: true
      - id: check-added-large-files
        always_run: true

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black
        always_run: true
        entry: black --color --skip-magic-trailing-comma --config=config/formatter/.black .
        pass_filenames: false
        language: system
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [
          --count,
          --color=always,
          --config=config/linter/.flake8,
          --exclude=netarmageddon/utils/banners.py
        ]
        always_run: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --warn-unused-ignores --show-column-numbers --show-error-code-links --pretty --show-absolute-path --exclude=netarmageddon/utils/banners.py --config=config/linter/.mypy.ini .
        language: system
        types: [python]
        always_run: true
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0
    hooks:
      - id: clang-format
        files: netarmageddon/core/traffic_c/.*\.(c|h)$
        args: [
          -style=file
          ]
        additional_dependencies: ['clang-format==14.0.0']
        exclude: \.(o|so|pcap)$
        always_run: true

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: scripts/run-clang-tidy.sh
        files: netarmageddon/core/traffic_c/.*\.(c|h)$
        language: system
        always_run: true
        pass_filenames: true

  - repo: local
    hooks:
      - id: update-README
        name: Update help in README
        entry: make generate_help
        language: system
        files: ^netarmageddon/
        stages: [pre-commit]
        always_run: true
