repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [
          --color,
          --check,
          --skip-magic-trailing-comma,
          --config=config/formatter/.black,
          ]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [
          --check,
          --settings-path=config/formatter/.isort.cfg
          ]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [
          --count,
          --color=always,
          --config=config/linter/.flake8,
          --exclude=netarmageddon/utils/banners.py
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        args: [
          --config=config/linter/.mypy.ini,
          --warn-unused-ignores,
          --show-column-numbers,
          --show-error-code-links,
          --pretty,
          --show-absolute-path,
          --exclude=netarmageddon/utils/banners.py
          ]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0
    hooks:
      - id: clang-format
        args: [-i, -style=file]
        files: netarmageddon/core/traffic_c/.*\.(c|h)$
        additional_dependencies: ['clang-format==14.0.0']
        exclude: \.(o|so|pcap)$

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        args: [
          --config-file=netarmageddon/core/traffic_c/.clang-tidy,
          -p=netarmageddon/core/traffic_c,
          --extra-arg=-Wno-unknown-warning-option,
          --extra-arg=-Wno-unused-command-line-argument
        ]
        language: system
        files: netarmageddon/core/traffic_c/.*\.(c|h)$
