site_name: NetArmageddon
nav:
  - Home: README.md
  - Usage: usage.md
  - Development: development.md
  - API Reference: api.md
  - Architecture: architecture.md
  - Testing Strategy: testing.md
  - Contributing: CONTRIBUTING.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
