name: CI Pipeline

on: [push, pull_request]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clean Python cache
        run: |
          pip cache purge

      - name: Clean everything
        run: |
          make clean

      - name: Install dependencies
        run: |
          make install

      - name: Check formatting
        run: |
          make format
          make c-format
          git diff --exit-code --name-only

      - name: Run linters
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        run: |
          make lint
          make c-lint

      - name: Run tests with coverage
        run: |
          make test
          make c-test
